### ISSUE TITLE
4. Encryption/Decryption

### ISSUE THREAD

**Issue by MikeBlu** [Tri11Paragon/COSC-4P14-Lab#4]
◦ Person A writes something; Person B sees that something; an eavesdropper mid-stream wouldn't understand it
◦ Feel free to simply connect openssl
◦ 'Strength' of encryption isn't a factor. It's fine to hardcode passwords/keys, if used
◦ It's acceptable to do trivial transformations
▪ e.g. simplying XOR'ing every byte, or running text through base64 encoding
▪ The only requirement is to make it unreadable at a casual glance

**Comment by Tri11Paragon** [comment]
Used java base64 encrypt
